# Homebrew formula for dog.
#
# Generated by scripts/render_packaging.py from packaging/homebrew/dog.rb in
# https://github.com/l1a/dog and pushed to this tap by scripts/publish_packaging.py. Change the
# template there, not this file. The release version in the url and the sha256 are the only
# release-specific values: they are supplied when the formula is published, from the tag and from
# the tarball actually downloaded, so nothing in the repository records a release and nothing can
# drift from one.
#
# WHY A TAP RATHER THAN homebrew-core: core has notability requirements this project does not
# meet, and the tap needs no approval. Moving to core later is a separate decision.
#
# WHY A SOURCE BUILD AND NOT A BOTTLE: a bottle is a prebuilt binary that CI must build, sign
# and upload per macOS version and architecture. This builds from source and needs only Rust
# and pandoc, which Homebrew supplies as build-time dependencies.
class Dog < Formula
  desc "Command-line DNS client"
  homepage "https://github.com/l1a/dog"
  url "https://github.com/l1a/dog/archive/refs/tags/v@VERSION@.tar.gz"
  sha256 "@SHA256@"
  license "GPL-3.0-or-later"
  head "https://github.com/l1a/dog.git", branch: "master"

  depends_on "pandoc" => :build
  depends_on "rust" => :build

  def install
    # `std_cargo_args` already passes `--locked` (with `--root` and `--path`), so it must not be
    # repeated: cargo rejects a duplicate. `--locked` is load-bearing: Homebrew builds with
    # network access and no vendored dependencies, so Cargo.lock is the only thing pinning
    # what is built to what CI tested.
    #
    # The package is `dogdns` but the only [[bin]] is `dog`, so this installs `dog`.
    system "cargo", "install", *std_cargo_args

    # man/dog.1.md carries a literal VERSION placeholder, which `just man` also substitutes.
    (buildpath/"dog.1.md").write (buildpath/"man/dog.1.md").read.gsub("{{VERSION}}", version.to_s)
    system "pandoc", "--standalone", "-f", "markdown", "-t", "man", "-o", "dog.1", "dog.1.md"
    man1.install "dog.1"

    # Generated by the binary that was just built, so completions cannot disagree with the CLI
    # they describe. `--completions=<shell>` is the flag's `=`-joined form, which is what
    # `shell_parameter_format` produces here. `shells:` is omitted: bash/zsh/fish is the
    # default, and passing it explicitly is flagged by `brew audit --strict` as redundant.
    generate_completions_from_executable(bin/"dog", shell_parameter_format: "--completions=")
  end

  test do
    # No DNS query: a Homebrew test machine may have no network, and the answer would depend
    # on it. `--version` proves the binary runs.
    output = shell_output("#{bin}/dog --version")
    assert_match "command-line DNS client", output

    # ...and, for a release, that it is the version the formula claims. A --HEAD build is named
    # HEAD-<sha> while the binary reports Cargo.toml's version, so the two can only be compared
    # for a release. CI installs with --HEAD (there is no tag to build before a release exists),
    # which is why this is guarded and not simply asserted.
    assert_match version.to_s, output unless version.head?

    # The completions the CLI generates must be real, and the man page must carry the real
    # version in its footer. A bare existence check would pass on an unsubstituted placeholder.
    assert_match "_dog", shell_output("#{bin}/dog --completions bash")
    assert_path_exists man1/"dog.1"
    assert_match version.to_s, (man1/"dog.1").read
  end
end
