[package]
name = "dns-transport"
version = "0.2.0-pre"
authors = ["Benjamin Sago <ogham@bsago.me>"]
edition = "2018"

[lib]
doctest = false
test = false


[dependencies]

# dns wire protocol
dns = { path = "../dns" }

# logging
log = "0.4"

# tls networking

# http response parsing
httparse = { version = "1.10", optional = true }

rustls = { version = "0.23", optional = true }

webpki = { version = "0.22.4", optional = true }

webpki-roots = { version = "1.0.2", optional = true }

[features]
default = []  # these are enabled in the main dog crate

with_https = ["httparse"]

with_rustls = ["rustls", "webpki-roots", "webpki"]
